# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180101_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post_images/None/no-img.jpg', null=True, upload_to='post_images/'),
        ),
    ]
