# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180101_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/none/no-img.jpg', null=True, upload_to='post_images/'),
        ),
    ]
